{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "course-service.envSecretName" . }}
  labels:
    {{- include "course-service.labels" . | nindent 4 }}
type: Opaque
{{- /*
  Используем stringData (а не data): значения пишем в открытом виде,
  k8s сам закодирует их в base64 при сохранении.
*/}}
stringData:
  .env: |-
    LOG_LEVEL={{ .Values.config.logLevel }}
    LOG_FILE_PATH={{ .Values.config.logFilePath }}
    HTTP_SERVER_ADDR={{ .Values.config.httpServerAddr }}
    POSTGRES_HOST={{ .Values.config.postgres.host }}
    POSTGRES_PORT={{ .Values.config.postgres.port }}
    POSTGRES_USER={{ .Values.config.postgres.user }}
    POSTGRES_PASSWORD={{ .Values.secrets.postgresPassword }}
    POSTGRES_DB={{ .Values.config.postgres.db }}
    POSTGRES_SSLMODE={{ .Values.config.postgres.sslmode }}
    POSTGRES_MIGRATIONS_PATH={{ .Values.config.postgres.migrationsPath }}
    {{- if .Values.config.kafka.brokers }}
    KAFKA_BROKERS={{ join "," .Values.config.kafka.brokers }}
    {{- end }}
{{- end }}
