{{/*
ServiceAccount — это идентичность пода в кластере (как пользователь в ОС).
Когда под обращается к API Kubernetes, он делает это от имени своего SA.
Сейчас приложению API k8s не нужен, но иметь свой SA — хорошая практика
(потом проще навесить RBAC, если что-то понадобится).
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "course-service.serviceAccountName" . }}
  labels:
    {{- include "course-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
