{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users-service.envSecretName" . }}
  labels:
    {{- include "users-service.labels" . | nindent 4 }}
type: Opaque
{{- /*
  Используем stringData (а не data): значения пишем в открытом виде,
  k8s сам закодирует их в base64 при сохранении.
*/}}
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end -}}
